Laboratorio3/Laboratorio3/Models/ErrorViewModel.cs
namespace Laboratorio3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Laboratorio3/Laboratorio3/Models/MovieModel.cs
namespace Laboratorio3.Models
{
    public class MovieModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public DateTime ReleasedDate { get; set; }

    }
}

Laboratorio3/Laboratorio3/Models/SongModel.cs
namespace Laboratorio3.Models
{
    public class SongModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public DateTime ReleasedDate { get; set; }

        public string Author { get; set; }
        public string Album { get; set; }

    }
}

Laboratorio3/Laboratorio3/Controllers/HomeController.cs
using Laboratorio3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Laboratorio3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Laboratorio3/Laboratorio3/Controllers/MovieController.cs
using Laboratorio3.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace Laboratorio3.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            var movies = GetListOfMovies();
            ViewBag.MainTitle = "List of my favourite films";
            return View(movies);
        }

        private List<MovieModel> GetListOfMovies()
        {
            List<MovieModel> movies = new List<MovieModel>();
            movies.Add(new MovieModel
            {
                Id = 1,
                Name = "Pulp Fiction",
                Genre = "Crime/Drama",
                ReleasedDate = new DateTime(1994, 10, 14)
            });
            movies.Add(new MovieModel
            {
                Id = 2,
                Name = "Toy Story",
                Genre = "Family/Comedy",
                ReleasedDate = new DateTime(1995, 11, 22)
            });
            movies.Add(new MovieModel
            {
                Id = 3,
                Name = "Mulan",
                Genre = "Family/Comedy",
                ReleasedDate = new DateTime(1998, 06, 19)
            });

            return movies;

        }
    }
}

Laboratorio3/Laboratorio3/Controllers/SongController.cs
using Laboratorio3.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace Laboratorio3.Controllers
{
    public class SongController : Controller
    {
        public IActionResult Index()
        {
            var song = GetSong();
            ViewBag.MainTitle = "My Favourite Song";
            return View(song);
        }

        private SongModel GetSong()
        {
            var song = new SongModel();
            song.Name = "Radioactive";
            song.Genre = "Alternative Rock";
            song.Author = "Imagine Dragons";
            song.Album = "Night Visions (Deluxe)";
            song.ReleasedDate = new DateTime(2014, 01, 27);

            return song;
        }
    }
}

Laboratorio3/Laboratorio3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Laboratorio3/Laboratorio3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorio3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laboratorio3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratorio3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Song" asp-action="Index">Favourite Song</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Laboratorio3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Laboratorio3/Laboratorio3/Views/Song/Index.cshtml
@model Laboratorio3.Models.SongModel


@{
    ViewData["Title"] = "Song";
}

<h1>@ViewBag.MainTitle</h1>

<div>
    <table class="table">
        <tr>
            <th>Song Title</th>
            <td>@Model.Name</td>
        </tr>

        <tr>
            <th>Author</th>
            <td>@Model.Author</td>
        </tr>

        <tr>
            <th>Gender</th>
            <td>@Model.Genre</td>
        </tr>

        <tr>
            <th>Album</th>
            <td>@Model.Album</td>
        </tr>

        <tr>
            <th>Released Date</th>
            <td>@Model.ReleasedDate</td>
        </tr>
    </table>
</div>
<div>
    <button>I am a button</button>
</div>

Laboratorio3/Laboratorio3/Views/movie/Index.cshtml
@model List<Laboratorio3.Models.MovieModel>

@{
    ViewData["Title"] = "Movies";
}

<h1>@ViewBag.MainTitle</h1>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>Movie Title</th>
                <th>Gender</th>
                <th>Released Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Genre</td>
                    <td>@item.ReleasedDate</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <button>I am a button</button>
</div>